jobs:
  sonarQube:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-8.0.1.6346-linux-x64.zip
          unzip sonar-scanner-cli-8.0.1.6346-linux-x64.zip -d $HOME
          echo "$HOME/sonar-scanner-8.0.1.6346-linux-x64/bin" >> $GITHUB_PATH

      - name: Run SonarScanner
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner \
          -Dsonar.projectKey=mi_proyecto_seguro \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.token=$SONAR_TOKEN \
          -Dsonar.python.version=3.10
